apiVersion: v1
kind: Service
metadata:
  name: coraza-operator-grpc
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: coraza-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: coraza-operator
  ports:
    - name: grpc
      port: 9443
      targetPort: 9443
      protocol: TCP
