apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "coraza-operator.serviceAccountName" . }}
  namespace: {{ include "coraza-operator.namespace" . }}
  labels:
    {{- include "coraza-operator.labels" . | nindent 4 }}
