apiVersion: v1
kind: Service
metadata:
  name: {{ include "coraza-operator.fullname" . }}-metrics
  namespace: {{ include "coraza-operator.namespace" . }}
  labels:
    {{- include "coraza-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "coraza-operator.selectorLabels" . | nindent 4 }}
  ports:
  - name: metrics
    port: {{ .Values.metrics.port }}
    targetPort: metrics
    protocol: TCP
