---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - waf.gtrfc.com
  resources:
  - clustersecrules
  - rulesets
  - secrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - waf.gtrfc.com
  resources:
  - clustersecrules/status
  - engines/status
  - rulesets/status
  - secrules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - waf.gtrfc.com
  resources:
  - engines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
