apiVersion: waf.gtrfc.com/v1
kind: ClusterSecRules
metadata:
  labels:
    app.kubernetes.io/name: coraza-operator
    app.kubernetes.io/managed-by: kustomize
  name: clustersecrules-sample
spec:
  # TODO(user): Add fields here
