// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: config.proto

package wafv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EngineNamespace string                 `protobuf:"bytes,1,opt,name=engine_namespace,json=engineNamespace,proto3" json:"engine_namespace,omitempty"`
	EngineName      string                 `protobuf:"bytes,2,opt,name=engine_name,json=engineName,proto3" json:"engine_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetEngineNamespace() string {
	if x != nil {
		return x.EngineNamespace
	}
	return ""
}

func (x *SubscribeRequest) GetEngineName() string {
	if x != nil {
		return x.EngineName
	}
	return ""
}

type RuleSetBundle struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RulesetName     string                 `protobuf:"bytes,1,opt,name=ruleset_name,json=rulesetName,proto3" json:"ruleset_name,omitempty"`             // RuleSet object name
	Sha256          string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`                                          // sha256 of compiled
	CompiledSeclang string                 `protobuf:"bytes,3,opt,name=compiled_seclang,json=compiledSeclang,proto3" json:"compiled_seclang,omitempty"` // full compiled bundle
	GeneratedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RuleSetBundle) Reset() {
	*x = RuleSetBundle{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleSetBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleSetBundle) ProtoMessage() {}

func (x *RuleSetBundle) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleSetBundle.ProtoReflect.Descriptor instead.
func (*RuleSetBundle) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *RuleSetBundle) GetRulesetName() string {
	if x != nil {
		return x.RulesetName
	}
	return ""
}

func (x *RuleSetBundle) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *RuleSetBundle) GetCompiledSeclang() string {
	if x != nil {
		return x.CompiledSeclang
	}
	return ""
}

func (x *RuleSetBundle) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

type EnrollRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SaToken         string                 `protobuf:"bytes,1,opt,name=sa_token,json=saToken,proto3" json:"sa_token,omitempty"`                         // projected SA JWT
	EngineNamespace string                 `protobuf:"bytes,2,opt,name=engine_namespace,json=engineNamespace,proto3" json:"engine_namespace,omitempty"` // claimed identity (must match token's SA namespace)
	EngineName      string                 `protobuf:"bytes,3,opt,name=engine_name,json=engineName,proto3" json:"engine_name,omitempty"`                // claimed engine name
	CsrDer          []byte                 `protobuf:"bytes,4,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`                            // ASN.1 DER-encoded CertificateRequest with the engine's public key
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *EnrollRequest) GetSaToken() string {
	if x != nil {
		return x.SaToken
	}
	return ""
}

func (x *EnrollRequest) GetEngineNamespace() string {
	if x != nil {
		return x.EngineNamespace
	}
	return ""
}

func (x *EnrollRequest) GetEngineName() string {
	if x != nil {
		return x.EngineName
	}
	return ""
}

func (x *EnrollRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

type EnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientCertPem []byte                 `protobuf:"bytes,1,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"`
	CaCertPem     []byte                 `protobuf:"bytes,2,opt,name=ca_cert_pem,json=caCertPem,proto3" json:"ca_cert_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *EnrollResponse) GetClientCertPem() []byte {
	if x != nil {
		return x.ClientCertPem
	}
	return nil
}

func (x *EnrollResponse) GetCaCertPem() []byte {
	if x != nil {
		return x.CaCertPem
	}
	return nil
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\x06waf.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"^\n" +
	"\x10SubscribeRequest\x12)\n" +
	"\x10engine_namespace\x18\x01 \x01(\tR\x0fengineNamespace\x12\x1f\n" +
	"\vengine_name\x18\x02 \x01(\tR\n" +
	"engineName\"\xb4\x01\n" +
	"\rRuleSetBundle\x12!\n" +
	"\fruleset_name\x18\x01 \x01(\tR\vrulesetName\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\x12)\n" +
	"\x10compiled_seclang\x18\x03 \x01(\tR\x0fcompiledSeclang\x12=\n" +
	"\fgenerated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\"\x8f\x01\n" +
	"\rEnrollRequest\x12\x19\n" +
	"\bsa_token\x18\x01 \x01(\tR\asaToken\x12)\n" +
	"\x10engine_namespace\x18\x02 \x01(\tR\x0fengineNamespace\x12\x1f\n" +
	"\vengine_name\x18\x03 \x01(\tR\n" +
	"engineName\x12\x17\n" +
	"\acsr_der\x18\x04 \x01(\fR\x06csrDer\"X\n" +
	"\x0eEnrollResponse\x12&\n" +
	"\x0fclient_cert_pem\x18\x01 \x01(\fR\rclientCertPem\x12\x1e\n" +
	"\vca_cert_pem\x18\x02 \x01(\fR\tcaCertPem2\x88\x01\n" +
	"\rConfigService\x12>\n" +
	"\tSubscribe\x12\x18.waf.v1.SubscribeRequest\x1a\x15.waf.v1.RuleSetBundle0\x01\x127\n" +
	"\x06Enroll\x12\x15.waf.v1.EnrollRequest\x1a\x16.waf.v1.EnrollResponseB@Z>github.com/guided-traffic/coraza-operator/proto/waf/v1;wafv1pbb\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_config_proto_goTypes = []any{
	(*SubscribeRequest)(nil),      // 0: waf.v1.SubscribeRequest
	(*RuleSetBundle)(nil),         // 1: waf.v1.RuleSetBundle
	(*EnrollRequest)(nil),         // 2: waf.v1.EnrollRequest
	(*EnrollResponse)(nil),        // 3: waf.v1.EnrollResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_config_proto_depIdxs = []int32{
	4, // 0: waf.v1.RuleSetBundle.generated_at:type_name -> google.protobuf.Timestamp
	0, // 1: waf.v1.ConfigService.Subscribe:input_type -> waf.v1.SubscribeRequest
	2, // 2: waf.v1.ConfigService.Enroll:input_type -> waf.v1.EnrollRequest
	1, // 3: waf.v1.ConfigService.Subscribe:output_type -> waf.v1.RuleSetBundle
	3, // 4: waf.v1.ConfigService.Enroll:output_type -> waf.v1.EnrollResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
